---
title: "horizon intelligence: summary and keywords produced by a LLM"
output: html_notebook
---


```{r}
library(tidyverse)

library(httr)
library(jsonlite)

selected_esv_topic <- "electron microscopy"
destination_path <- "./data/filtered-m/"

```


```{r}
names <- read_csv(paste0(destination_path, 'prjs.csv'))%>% 
                      select(projID, acronym)%>% arrange(projID)

df <- read_csv(paste0(destination_path,'prj_objectives.csv')) %>% 
  arrange(projID) %>%
  merge(names) %>%
  mutate(text = paste("Project", acronym, ". ", objective)) %>%
  select(projID, text)




```


```{r}


# Define the API endpoint
url <- "https://api.openai.com/v1/engines/gpt-3.5-turbo-instruct/completions"
# fast and unexpansive model
# https://openai.com/api/pricing/
    
# Define the headers
headers <- add_headers(
  "Content-Type" = "application/json",
  "Authorization" = paste("Bearer", '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')
)

prompt = "Given the following text describing project objectives, generate a sentence summarizing project objectives. 
Add a list of single-word keywords that capture the technological focus of the project. each keyword is composed of 1 or 2 words.
Format the output as in this example
SUMMARY: [project name] aims to ...
KEYWORDS: [keyword1]; [keyword2];...
"

# prompt <- 'Given the text describing project objectives, produce a sentence that classifies the project into one of the following categories:
# a)Project [name] is focused specifically on developing technology for [hydrogen or fuel cells]
# .
# b)Project [name] is focused on [which technology] and hydrogen is one of the applications.
# c)Project [name] is focused on market uptake of [hydrogen or renewable energy]
# If none of the above, output is "Project [name] is focused on [brief description of the focus]."  '

# prompt <- 'Given the text describing project objectives, produce a sentence that specifies if the text includes one or more of the folowing words: "fuel cell",  PEMFC, SOFC, PAFC, AFC, MCFC, DMFC, or RFC.
# The output is formatted as either a) or b).
# a) No.
# b) YES:[list which acronyms are present]. '

df$result <- NA



```


```{r}
nsample <- nrow(df)
for (i in 1:nsample) {
    
    print(paste(i, "processing", df$projID[i]))
    
    text = df$text[i]
    
    data <- list("prompt" = paste(prompt, text),"max_tokens" = 100)
    
    json_data <- toJSON(data, auto_unbox = TRUE)
    
    response <- POST(url, headers, body = json_data)
    
    parsed_response <- content(response, "parsed")

    result <- parsed_response$choices[[1]]$text
    
    print(result)
    
    df$result[i] <- result
  
}
```




```{r}

df1 <- df
df1$result <- gsub("^\\s+|\\s+$", "", df1$result) # Remove leading and trailing whitespace
df1$result <- gsub("\\s{2,}", " ", df1$result)    # Replace multiple spaces with a single space

df1$keywords <- gsub(".*KEYWORDS:\\s*", "", df1$result)
df1$result <- gsub("\\s*KEYWORDS:.*", "", df1$result)



df1 %>%  
    rename(summary = result)%>%
    write_delim(paste0(destination_path, "AI_summary.csv"), 
                     delim = "|")


```


 
 