---
title: "horizon intelligence: summary and keywords produced by a LLM"
output: html_notebook
---


```{r}
library(tidyverse)

library(httr)
library(jsonlite)

source('./code/hi_0_parameters.R')

```


```{r}
names <- read_csv(paste0(destination_path, 'prjs.csv'))%>% 
                      select(projID, acronym)%>% arrange(projID)

df <- read_csv(paste0(destination_path,'prj_objectives.csv')) %>% 
  arrange(projID) %>%
  merge(names) %>%
  mutate(text = paste("Project", acronym, ". ", objective)) %>%
  select(projID, text)




```


```{r}

source('./api_url_key/api_url_key.R')

# prompt for microscopy

# prompt = "Given the following text describing project objectives, generate a sentence summarizing project objectives. 
# Add a list of single-word keywords that capture the technological focus of the project. each keyword is composed of 1 or 2 words.
# Format the output as in this example
# SUMMARY: [project name] aims to ...
# KEYWORDS: [keyword1]; [keyword2];...
# FOCUS: [project name] is focused on ...
# "

# prompt for hydrogen energy 
# prompt = "Given the following text describing project objectives, generate a sentence summarizing project objectives. 
# Add a list of single-word keywords that capture the technological focus of the project. each keyword is composed of 1 or 2 words.
# Add a comment on project focus: technology or market uptake? is hydrogen the core focus, or just one of the applications?
# Format the output as in this example
# SUMMARY: [project name] aims to ...
# KEYWORDS: [keyword1]; [keyword2];...
# FOCUS: [project name] is focused on ... 
# "
# 

# prompt for pandemics 
# 
# prompt = "Given the following text describing project objectives, generate a sentence summarizing project objectives. 
# Add a list of single-word keywords that capture the technological focus of the project. each keyword is composed of 1 or 2 words.
# Add a comment on project focus: focused on COVID-19 or more general?
# Format the output as in this example
# SUMMARY: [project name] aims to ...
# KEYWORDS: [keyword1]; [keyword2];...
# FOCUS: [project name] is focused on ... 
# "
# 
# prompt <- 'Given the text describing project objectives, produce a sentence that classifies the project into one of the following categories:
#  a)Project [name] is focused specifically on developing technology for [hydrogen or fuel cells]
# .
# b)Project [name] is focused on [which technology] and hydrogen is one of the applications.
# c)Project [name] is focused on market uptake of [hydrogen or renewable energy]
# If none of the above, output is "Project [name] is focused on [brief description of the focus]."  '

# prompt <- 'Given the text describing project objectives, produce a sentence that specifies if the text includes one or more of the folowing words: "fuel cell",  PEMFC, SOFC, PAFC, AFC, MCFC, DMFC, or RFC.
# The output is formatted as either a) or b).
# a) No.
# b) YES:[list which acronyms are present]. '


prompt <- "Analyze the following project objectives and categorize it into one of the two categories: hydrogen_tech or hydrogen_market.
1. 'hydrogen_market' if the project objectives are more focused on business models, market uptake, hydrogen valley, policy or hydrogen has a marginal role as potential application. 
2. 'hydrogen_tech' if the project objectives is about hydrogen related technology, physics, chemistry, engineering, or fuel cells.
Respond only with 'hydrogen_market' or 'hydrogen_tech'  .
Text to analyze:"




```


```{r}
df$result <- NA
nsample <- nrow(df)


for (i in 1:nsample) {
    
    text = df$text[i]
    
    data <- list("prompt" = paste(prompt, text),"max_tokens" = 200)
    
    json_data <- toJSON(data, auto_unbox = TRUE)
    
    response <- POST(url, headers, body = json_data)
    
    parsed_response <- content(response, "parsed")

    result <- parsed_response$choices[[1]]$text
    
    
    
    print(paste(i, "processing", df$projID[i], result))
    
    df$result[i] <- result
  
}
```

```{r}
i = 8
df$result[i]
df$text[i]

```



```{r}

# df1 <- df
# df1$result <- gsub("^\\s+|\\s+$", "", df1$result) 
# df1$result <- gsub("\\s{2,}", " ", df1$result)    # Replace multiple spaces with a single space
# # 
# df1$keywords <- gsub(".*KEYWORDS:\\s*", "", df1$result)
# df1$result <- gsub("\\s*KEYWORDS:.*", "", df1$result)

# df1 %>%  
#     rename(summary = result)%>%
#     # write_delim(paste0(destination_path, "AI_summary.csv"), 
#                      delim = "|")

df1 <- df |>
  mutate(tech = str_detect(tolower(result), "tech"))  

mean(df1$tech)

df1 %>%  
    write_delim(paste0(destination_path, "AI_cetegorical.csv"), 
                     delim = "|")


```


 
 