---
title: "figure networks"
format: html
editor: visual
---

```{r}
library(igraph)
library(tidyverse)
source('./code/hi_0_parameters.R')
source('./code/hi_functions.R')

```

```{r}
df<- data.frame()
for(yy in 2015:2029){
g <- read.graph(file = paste0('data/filtered-h/',yy,'.graphml'),format = 'graphml')
#g <- delete_edges(g, E(g)[weight == 0])
#g <- delete_vertices(g, degree(g) ==0)
df<- rbind(df, data.frame(
    year = yy,
    n_org = vcount(g),
    n_coll  = ecount(g),
    weight = sum(E(g)$weight)
))
}
print(df)
```

```{r}

df$color <- ifelse(df$year < 2024, "orange", ifelse(df$year == 2024, "red", "lightgray"))


pp<-ggplot(df, aes(x = n_org, y = n_coll)) +
  geom_point(shape = 21, stroke = 1, aes(fill = color, size = weight), alpha = .5) +  
  scale_size_continuous(range = c(1, 12)) +  # size of bubbles
      scale_fill_identity() +  # exact colors specified in the 'color' column
    
      geom_segment(aes(xend = lead(n_org), yend = lead(n_coll)), 
               linewidth = 0.5, color = "black",
               arrow = arrow(length = unit(0.2, "cm")),  # Add arrows
               na.rm = TRUE) +  # Remove NAs that may arise at the last row


    xlim(0,800)+ ylim(0,7000)+
    geom_text(data = subset(df, year %in% c(2015, 2022, 2024)), 
            aes(label = year), vjust = 0.5, hjust = -0.4, size = 4, color = "black") +  # Add labels for specified years
  
  labs(
    #title = "Bubble Chart: Number of Projects vs Number of Organizations with Arrows",
    x = "Number of Organizations",
    y = "Number of Collaborations",
    size = "Total Weight"
  ) +
  theme_minimal() + theme(aspect.ratio = .6)

pp 

png(paste0('./figures/5-community time/networksyears.png'), height = 300, width = 600, units = "px", bg = "white")
pp
dev.off()
```
