---
title: "figure4"
format: html
editor: visual
---

```{r}
library(igraph)
library(tidyverse)
library(communities)
library(cowplot)
library(magick) #png

source('./code/hi_0_parameters.R')
source('./code/hi_functions.R')

```

# function

```{r}
yy = 2024
met = "LD"
ar = .5

make_figure <- function(yy, met, param, tmax, ar) {
    gy <-
        igraph::read.graph(file = paste0(destination_path, yy, '.graphml'),format = 'graphml')
    
    plot_list <- c()
    
    ssp <- communities::solutions_space(gy,
                                        met = met,
                                        tmax = tmax,
                                        resolution = param)
    
    ssp <- quality_check(gy, ssp)
    
    ssp$data <- ssp$data %>%
        mutate(id = if_else(valid == FALSE, 
                               paste0("NV-",id), id))
    
    
    
    nn <- nrow(ssp$data) 
    
    plotssp <- communities::plot_sol_space(ssp)
    
    plot_list[[length(plot_list) + 1]] <- plotssp$pl2 +
        theme(legend.position =  "none") +
        labs(title = paste0("method: ", met)) +
        theme(panel.grid.minor = element_blank(),  
              aspect.ratio = ar)   
    
    plot_list[[length(plot_list) + 1]] <- plotssp$pl3 +
        theme(legend.position =  "none") +
        labs(x = "community size distribution", title = " ") +
        theme(panel.grid.minor = element_blank(),
              panel.grid.major = element_blank(),
              axis.text.y = element_blank(),  
              axis.ticks.y = element_blank(),
              aspect.ratio = ar)+
        ylim(0.5,nn+0.5) 
    
    return(plot_grid(
        plotlist = plot_list,
        ncol = 2,
        nrow = 1))

}

```

```{r}
# valid solutions with LD
gy <- igraph::read.graph(file = './data/filtered-h/2024.graphml',
format = 'graphml')
make_figure(yy = yy, met="LD", param= 0.1, tmax=20, ar = 0.2)
make_figure(yy = yy, met="LD", param= .99, tmax=20, ar = 0.2)
make_figure(yy = yy, met="LD", param= 2, tmax=20, ar = 0.2) 
```

# compare methods over time

```{r}
tmax = 100
all_results <- data.frame()

for (yy in 2015:2029){
    filename <- paste0(destination_path, yy, '.graphml')
    print(filename)
    gy <- igraph::read.graph(file = filename,format = 'graphml')
    
    for (met in c("LV", "LD", "LP", "IM", "WT")){

        
        ssp <- communities::solutions_space(gy,
                                        met = met,
                                        tmax = tmax,
                                        resolution = 
                                            if_else(met == "LV", 1.0, 1.5),
                                        IM.nb.trials = 1,
                                        WT.steps = 3)
        
        ssp <- quality_check(gy, ssp)
        
        n_valid_solutions <- ssp$data |> filter(valid == T) |> nrow()
        year_met_results <- ssp$data |> 
            select(k, k_n, mod, mu, int_conn, valid) |>
            mutate(year = factor(yy), met = met) |>
            mutate(n_valid_solutions = n_valid_solutions)
        
        
        all_results<- rbind(all_results, year_met_results)
        
    }
    
}

all_results <- all_results |> mutate(year = factor(year))
```

```{r}
all_results %>% ggplot(aes(x = year, y = n_valid_solutions, 
                           group = met, color = met, shape = met))+
    geom_point()+geom_line()

```

# 2020

```{r}
yy <-2020
p1<-make_figure(yy = yy, met="LV", param= 1.0, tmax=100, ar = 0.4)
p2<-make_figure(yy = yy, met="LD", param= 1.5, tmax=20, ar = 0.2)
p3<-make_figure(yy = yy, met="LP", param= 1.0, tmax=100, ar = 0.8)
p4<-make_figure(yy = yy, met="IM", param= 1.0, tmax=200, ar = 0.5)
p5<-make_figure(yy = yy, met="WT", param= 4.0, tmax=100, ar = 0.15)

p1
p2
p3
p4
p5

ggsave('./figures/4-explore-sol-space/figure-4-1-2020.png', 
       plot = p1, 
       width = 10, height = 3, dpi = 300)
 
ggsave('./figures/4-explore-sol-space/figure-4-2-2020.png', 
       plot = p2, 
       width = 10, height = 2, dpi = 300)

ggsave('./figures/4-explore-sol-space/figure-4-3-2020.png', 
       plot = p3, 
       width = 10, height = 5, dpi = 300)

ggsave('./figures/4-explore-sol-space/figure-4-4-2020.png', 
       plot = p4, 
       width = 10, height = 4, dpi = 300)

ggsave('./figures/4-explore-sol-space/figure-4-5-2020.png', 
       plot = p5, 
       width = 10, height = 1.5, dpi = 300)

img1 <- image_read('./figures/4-explore-sol-space/figure-4-1-2020.png')
img2 <- image_read('./figures/4-explore-sol-space/figure-4-2-2020.png')
img3 <- image_read('./figures/4-explore-sol-space/figure-4-3-2020.png')
img4 <- image_read('./figures/4-explore-sol-space/figure-4-4-2020.png')
img5 <- image_read('./figures/4-explore-sol-space/figure-4-5-2020.png')

# Combine the images into a single column
combined_img <- image_append(c(img1, img2, img3, img4, img5), stack = TRUE)

combined_img
# Save the combined image
image_write(combined_img, 
            path = "./figures/4-explore-sol-space/figure-SSP-2020.png", 
            format = "png")
```

```{r}
yy <-2018
p1<-make_figure(yy = yy, met="LV", param= 1.0, tmax=100, ar = 0.4)
p2<-make_figure(yy = yy, met="LD", param= 0.5, tmax=100, ar = 0.2)
p3<-make_figure(yy = yy, met="LP", param= 1.0, tmax=20, ar = 0.8)
p4<-make_figure(yy = yy, met="IM", param= 1.0, tmax=100, ar = 0.5)
p5<-make_figure(yy = yy, met="WT", param= 4.0, tmax=100, ar = 0.15)

p1
p2
p3
p4
p5

ggsave('./figures/4-explore-sol-space/figure-4-1-2018.png', 
       plot = p1, 
       width = 10, height = 3, dpi = 300)
 
ggsave('./figures/4-explore-sol-space/figure-4-2-2018.png', 
       plot = p2, 
       width = 10, height = 2, dpi = 300)

ggsave('./figures/4-explore-sol-space/figure-4-3-2018.png', 
       plot = p3, 
       width = 10, height = 5, dpi = 300)

ggsave('./figures/4-explore-sol-space/figure-4-4-2018.png', 
       plot = p4, 
       width = 10, height = 4, dpi = 300)

ggsave('./figures/4-explore-sol-space/figure-4-5-2018.png', 
       plot = p5, 
       width = 10, height = 1.5, dpi = 300)

img1 <- image_read('./figures/4-explore-sol-space/figure-4-1-2018.png')
img2 <- image_read('./figures/4-explore-sol-space/figure-4-2-2018.png')
img3 <- image_read('./figures/4-explore-sol-space/figure-4-3-2018.png')
img4 <- image_read('./figures/4-explore-sol-space/figure-4-4-2018.png')
img5 <- image_read('./figures/4-explore-sol-space/figure-4-5-2018.png')

# Combine the images into a single column
combined_img <- image_append(c(img1, img2, img3, img4, img5), stack = TRUE)

combined_img
# Save the combined image
image_write(combined_img, 
            path = "./figures/4-explore-sol-space/figure-SSP-2018.png", 
            format = "png")
 
```

```{r}
```

```{r}
#install.packages("magick")

```
